### ISSUE TITLE
Steal `PlatformDependentOperation` from Topsoil

### ISSUE THREAD

**Issue by johnzeringue** [CIRDLES/Commons#4]
Since `PlatformDependentOperation` is now the only class in Topsoil outside of `org.cirdles.topsoil` (and rightfully so), it seems natural to move its functionality here.

This consists of two parts (the first of which satisfies this issue):
1. Complete a pull request here that provides a nice reimplementation of the functionality in Topsoil.
2. Complete a pull request for Topsoil that removes `PlatformDependentOperation` and replaces it with the solution here.

However, I think the new version should do the following:
- Have `PlatformDependentOperation` implement a functional interface `Operation`. `Operation` would have one method, `public R perform(T input)`. This involves changing the original class's interface and generics.
- Add a new class to determine the current platform and have it compose `PlatformDependentOperation`.
- Have a `package-private` constructor that takes a `Platform` (which would need to be created) in addition to a `public` default one. This will allow `PlatformDependentOperation` to be exhaustively tested.
- Add appropriate unit tests.

Of course, this is a useful abstraction that's worth getting right, so the above will likely change as we explore the solution space.

This is an excellent project for younger CIRDLErS or new contributors. Comment if you're interested.

**Comment by bowring** [comment]
Great idea - I will pass the word in Wednesday's meetings.

On Tue, Jun 2, 2015 at 1:27 AM, John Zeringue notifications@github.com
wrote:

> Since PlatformDependentOperation is now the only class in Topsoil outside
> of org.cirdles.topsoil (and rightfully so), it seems natural to move its
> functionality here.
> 
> This consists of two parts (the first of which satisfies this issue):
> 1. Complete a pull request here that provides a nice reimplementation
>    of the functionality in Topsoil.
> 2. Complete a pull request for Topsoil that removes
>    PlatformDependentOperation and replaces it with the solution here.
> 
> However, I think the new version should do the following:
> - Have PlatformDependentOperation implement a functional interface
>   Operation. Operation would have one method, public R perform(T input).
>   This involves changing the original class's interface and generics.
> - Add a new class to determine the current platform and have it
>   compose PlatformDependentOperation.
> - Have a package-private constructor that takes a Platform (which
>   would need to be created) in addition to a public default one. This
>   will allow PlatformDependentOperation to be exhaustively tested.
> - Add appropriate unit tests.
> 
> Of course, this is a useful abstraction that's worth getting right, so the
> above will likely change as we explore the solution space.
> 
> This is an excellent project for younger CIRDLErS or new contributors.
> Comment if you're interested.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CIRDLES/Commons/issues/4.

## 

Jim Bowring
C. Richard Crosby Distinguished Teaching Co-Chair
Principal Investigator, www.CIRDLES.org, www.github.com/cirdles

Computer Science
College of Charleston
66 George Street
Charleston, SC 29424

Google Voice: 843.608.1399 (preferred)
Google Email: bowring@gmail.com

Office:
Harbor Walk East (360 Concord Street) Room 308
843.953.0805
http://stono.cs.cofc.edu/~bowring/
bowringj@cofc.edu

R. Buckminster Fuller (1972):
If humanity is to survive aboard our planet, it must become universally
literate and preoccupied with inherently cooperative Comprehensive
Anticipatory Design Science in which every human is concerned with
accomplishing the comfortably sustainable well-faring of all other humans.

**Comment by johnzeringue** [comment]
This issue is no longer directly relevant as `PlatformDependentOperation` has been replaced over in Topsoil. However, the replacement, `PlatformDependentProvider`, might still be a good project for someone down the road.
